/**
 * ITvCableIntegrationService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.app.tvp.cas.cliente;

public interface ITvCableIntegrationService extends java.rmi.Remote {
    public com.app.tvp.cas.cliente.objetos.InstallResponse install(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, com.app.tvp.cas.cliente.objetos.SettopBox settopBox, java.lang.String[] packs, java.lang.String masterCard, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.DisconnectResponse disconnect(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.UpdateFirmwareResponse updateFirmware(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.SendMessageResponse sendMessage(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String message, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.UpdatePinResponse updatePin(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String pin, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.ReSendKeyResponse reSendKey(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.RemovePacksResponse removePacks(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String[] packs, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.AddPacksResponse addPacks(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String[] packs, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.UninstallResponse uninstall(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.ReconnectResponse reconnect(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String[] packs, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.EstatusResponse status(java.lang.String userName, java.lang.String password) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.ReScanChannelsResponse reScanChannels(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.AddCarrierResponse addCarrier(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String carrier, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.ViewSetTopBoxIDResponse viewSetTopBoxID(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.ResetSetTopBoxResponse resetSetTopBox(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.UpdateCodeZoneResponse updateCodeZone(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String code, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.RebootSetTopBoxResponse rebootSetTopBox(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.ForceUpdateFirmwareResponse forceUpdateFirmware(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.UpdateControlParentallResponse updateControlParentall(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String pin, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.UpdateMenuPassResponse updateMenuPass(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String pin, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.EGetSmartCardsInfoResponse getSmartCardsInfo(java.lang.String userName, java.lang.String password) throws java.rmi.RemoteException;
    public com.app.tvp.cas.cliente.objetos.EGetInformationResponse getInformation(java.lang.String userName, java.lang.String password, java.lang.String sequence, java.lang.String smartCards, java.lang.String userId, java.lang.String referenceNumber, java.lang.String notes, java.lang.String customerId, java.lang.String zone) throws java.rmi.RemoteException;
}
